apiVersion: argoproj.io/v1alpha
kind: Application
metadata:
  name: app-of-apps
spec:
  destination:
    name: in-cluster
    namespace: argocd
  source:
    path: ''
    repoURL: 'https://github.com/Andre-Oliveira-96/gw-yamls.git'
    targetRevision: HEAD
  project: default
