apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong
  namespace: kong
spec:
  destination:
    namespace: kong
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: charts/kong
    repoURL: "https://github.com/Andre-Oliveira-96/gw-yamls.git"
    targetRevision: HEAD
